config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :customers
  resources :books
  resources :usages, only: [:index, :create, :destroy]
  resources :courses, only: [:index, :create, :destroy]
  resources :tablenumbers, only: [:index, :create, :destroy]
  root :to => "homes#top"
  get "/about" => "homes#about"

  #顧客検索
  get 'search' => 'customers#search'

  # get ''
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :customer
  belongs_to :course, optional: true
  belongs_to :usage, optional: true
  belongs_to :tablenumber, optional: true
  accepts_attachments_for :tablenumbers
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :books
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :books, dependent: :destroy

  def self.search(keyword)
    where(["name like? OR phone_num like?", "%#{keyword}%", "%#{keyword}%"])
  end
end

app/models/tablenumber.rb
class Tablenumber < ApplicationRecord
  has_many :books
  validates :name, presence: true
end

app/models/usage.rb
class Usage < ApplicationRecord
  has_many :books
  validates :name, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_admin!

  def new
    @book = Book.new
  end

  def index
    @book = Book.new
      search_date = Date.today
      @books = Book.where(start_at: search_date.in_time_zone.all_day)
      @customer = Customer.new
      @customers = Customer.all
      @tablenumbers = Tablenumber.all
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if book_params[:date] == nil
      @book.tablenumber_id = book_params[:tablenumber_id]
    elsif book_params[:date] != nil && !book_params[:date].empty? && !book_params[:time].empty?
      @visit = book_params[:date] +" "+ book_params[:time]
      @book.start_at = @visit.to_datetime
      @book.people = book_params[:people]
      @book.allergy = book_params[:allergy]
      @book.other_allergy = book_params[:other_allergy]
      @book.note = book_params[:note]
    end

    if @book.save
      redirect_to books_path, notice: "予約情報が更新されました"
    end
  end

  def create
    customer = Customer.find_by("phone_num=? or name=?",book_params[:phone_num],book_params[:name])
    if customer.blank?
      customer = Customer.new(phone_num: book_params[:phone_num],name: book_params[:name], allergy: book_params[:allergy])
      if customer.save
        book = customer.books.new(people: book_params[:people], note: book_params[:note], allergy: book_params[:allergy], other_allergy: book_params[:other_allergy])
        @visit = book_params[:date] +" "+ book_params[:time]
        book.start_at = @visit.to_datetime
        book.save
        redirect_to books_path
      else
        render index
      end
    else
      book = customer.books.new(people: book_params[:people], note: book_params[:note], allergy: book_params[:allergy], other_allergy: book_params[:other_allergy])
      @visit = book_params[:date] +" "+ book_params[:time]
      book.start_at = @visit.to_datetime
      if book.save
        redirect_to books_path
      else
        redirect_to customers_path(phone_num:book_params[:phone_num], name: book_params[:name] )
      end
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "予約は取り消されました"
  end

private
  def book_params
    params.require(:book).permit(:phone_num, :name, :people, :allergy, :note, :date, :time, :other_allergy, :tablenumber_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/tablenumbers_controller.rb
class TablenumbersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @tablenumbers = Tablenumber.all
    @tablenumber = Tablenumber.new
    if params[:tablenumber_id].present?
      tablenumber = tablenumber.find(params[:id])
      @tablenumber.name = tablenumber.name
    end
  end

  def create
    @tablenumber = Tablenumber.new(tablenumber_params)
    @tablenumber.save
    @tablenumbers = Tablenumber.all
  end

    def destroy
    @tablenumber = Tablenumber.find(params[:id])
    @tablenumber.destroy
    redirect_to tablenumbers_path
  end

  private
  def tablenumber_params
    params.require(:tablenumber).permit(:name)
  end
end

app/controllers/tally_controller.rb
class TallyController < ApplicationController
end

app/controllers/usages_controller.rb
class UsagesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @usage = Usage.new
    @usages = Usage.all
  end

  def create
    @usage = Usage.new(course_params)
    @usage.save
    @usages = Usage.all
  end

  private
  def course_params
    params.require(:usage).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_courses_helper.rb
module BookCoursesHelper
end

app/helpers/book_usages_helper.rb
module BookUsagesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/table_nums_helper.rb
module TableNumsHelper
end

app/helpers/tablenumbers_helper.rb
module TablenumbersHelper
end

app/helpers/tally_helper.rb
module TallyHelper
end

app/helpers/usages_helper.rb
module UsagesHelper
end

app/views/tablenumbers/_tablenumbers.html.erb
<% tablenumbers.each do |t| %>
  <div class="card mb-1">
    <div class="card-body">
      <p class="card-text"><%= t.name %></p>
      <%= link_to '削除', tablenumber_path(t), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-outline-danger destroy_t_#{t.id}"%>
    </div>
  </div>
<% end %>

app/views/tablenumbers/create.js.erb
$('#input').val("");
$('#exampleModal').modal('hide');
$('.tablenumbers').html("<%= escape_javascript(render 'tablenumbers', tablenumbers: @tablenumbers) %>")

app/views/tablenumbers/index.html.erb
<div class="container mt-5">

  <div class="row">
    <div class="col-3 sidebar offset-1">
        <h2>TN一覧</h2>
<!--新規コース登録ボタン-->
<!-- Button trigger modal -->
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        TN追加
      </button>
    </div>
      <div class="col-5 tablenumbers offset-2">
        <%= render 'tablenumbers', tablenumbers: @tablenumbers %>
      </div>
    </div>
  </div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">新規TN登録</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with model: @tablenumber do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :name, "TN" %>
            <%= f.text_field :name, autofocus: true %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          <%= f.submit "登録する", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>