config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :customers
  resources :books
  resources :usages, only: [:index, :create, :destroy]
  resources :courses, only: [:index, :create, :destroy]
  resources :tablenumbers, only: [:index, :create, :destroy]
  root :to => "homes#top"
  get "/about" => "homes#about"

  #顧客検索
  get 'search' => 'customers#search'

  # get ''
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :customer
  belongs_to :course, optional: true
  belongs_to :usage, optional: true
  belongs_to :tablenumber, optional: true
  accepts_attachments_for :tablenumbers
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :books
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :books, dependent: :destroy

  def self.search(keyword)
    where(["name like? OR phone_num like?", "%#{keyword}%", "%#{keyword}%"])
  end
end

app/models/tablenumber.rb
class Tablenumber < ApplicationRecord
  has_many :books
  validates :name, presence: true
end

app/models/usage.rb
class Usage < ApplicationRecord
  has_many :books
  validates :name, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_admin!

  def new
    @book = Book.new
  end

  def index
    @book = Book.new
      search_date = Date.today
      @books = Book.where(start_at: search_date.in_time_zone.all_day)
      @customer = Customer.new
      @customers = Customer.all
      @tablenumbers = Tablenumber.all
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if book_params[:date] == nil
      @book.tablenumber_id = book_params[:tablenumber_id]
    elsif book_params[:date] != nil && !book_params[:date].empty? && !book_params[:time].empty?
      @visit = book_params[:date] +" "+ book_params[:time]
      @book.start_at = @visit.to_datetime
      @book.people = book_params[:people]
      @book.allergy = book_params[:allergy]
      @book.other_allergy = book_params[:other_allergy]
      @book.note = book_params[:note]
    end

    if @book.save
      redirect_to books_path, notice: "予約情報が更新されました"
    end
  end

  def create
    customer = Customer.find_by("phone_num=? or name=?",book_params[:phone_num],book_params[:name])
    if customer.blank?
      customer = Customer.new(phone_num: book_params[:phone_num],name: book_params[:name], allergy: book_params[:allergy])
      if customer.save
        book = customer.books.new(people: book_params[:people], note: book_params[:note], allergy: book_params[:allergy], other_allergy: book_params[:other_allergy])
        @visit = book_params[:date] +" "+ book_params[:time]
        book.start_at = @visit.to_datetime
        book.save
        redirect_to books_path
      else
        render index
      end
    else
      book = customer.books.new(people: book_params[:people], note: book_params[:note], allergy: book_params[:allergy], other_allergy: book_params[:other_allergy])
      @visit = book_params[:date] +" "+ book_params[:time]
      book.start_at = @visit.to_datetime
      if book.save
        redirect_to books_path
      else
        redirect_to customers_path(phone_num:book_params[:phone_num], name: book_params[:name] )
      end
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "予約は取り消されました"
  end

private
  def book_params
    params.require(:book).permit(:phone_num, :name, :people, :allergy, :note, :date, :time, :other_allergy, :tablenumber_id)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_admin!

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    @customer.save
    @customers = Customer.all
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customer_path(@customer.id), notice: "顧客情報が更新されました"
    else
      render :edit
    end
  end

  def show
    @customer = Customer.find(params[:id])
    @books = @customer.books
  end

  def index
    @customer = Customer.new
    @course = Course.new
    @book = Book.new
    if params[:customer_id].present?
      customer = Customer.find(params[:customer_id])
      @book.name = customer.name
      @book.customer = customer
      @book.customer.phone_num = customer.phone_num
      @book.allergy = customer.allergy
    end

    if params[:name].present?
      @serch_result = Customer.where("phone_num=? or name=?",params[:phone_num],params[:name])
    elsif params[:keyword].present?
      @serch_result = Customer.search(params[:keyword])
      @keyword = params[:keyword]
    else
      @serch_result = Customer.all
    end
    @customers = Customer.all.page(params[:page]).per(15)
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to customers_path, notice: "顧客情報は削除されました"
  end


private

  def customer_params
    params.require(:customer).permit(:name, :phone_num, :address, :allergy, :note, :is_active, :age, :book_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/tally_controller.rb
class TallyController < ApplicationController
end

app/controllers/usages_controller.rb
class UsagesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @usage = Usage.new
    @usages = Usage.all
  end

  def create
    @usage = Usage.new(course_params)
    @usage.save
    @usages = Usage.all
  end

  private
  def course_params
    params.require(:usage).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_courses_helper.rb
module BookCoursesHelper
end

app/helpers/book_usages_helper.rb
module BookUsagesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/table_nums_helper.rb
module TableNumsHelper
end

app/helpers/tablenumbers_helper.rb
module TablenumbersHelper
end

app/helpers/tally_helper.rb
module TallyHelper
end

app/helpers/usages_helper.rb
module UsagesHelper
end

app/views/customers/_customers.html.erb
<table class = "table">
  <thead>
    <tr>
      <th></th>
      <th>顧客ID</th>
      <th>名前</th>
      <th>電話番号</th>
    </tr>
  </thead>
  <tbody>
    <% customers.each do |c| %>
    <tr>
      <td>
        <%= link_to "新規予約作成", customers_path(customer_id: c.id), remote: true, class: "btn btn-primary" %>
      </td>
      <td class="customer_id"><%= c.id %></td>
      <td><%= link_to c.name, customer_path(c), class: "c_#{c.id}" %> 様</td>
      <td><%= c.phone_num %></td>
    </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </tfoot>
</table>

app/views/customers/_form.html.erb
<%= f.label :name %><br>
<%= f.text_field :name, autofocus: true, class: "form-field" %><br>
<%= f.label :phone_num %><br>
<%= f.telephone_field :phone_num, class: "form-field" %>（ハイフンなし）<br>
<%= f.label :address %><br>
<%= f.text_field :address, class: "form-field" %><br>
<%= f.label :allergy %><br>
<%= f.text_field :allergy, class: "form-field" %><br>
<%= f.label :note %><br>
<%= f.text_area :note, class: "form-field" %><br>
<%= f.label :age %><br>
<%= f.text_field :age, class: "form-field" %>歳<br>

app/views/customers/_modal_customer.html.erb
   <!-- Modal -->
  <div class="modal fade" id="customerModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">新規顧客登録</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <%= form_with model: customer do |f| %>
          <div class="modal-body">
            <div class="form-group">
              <%= render 'form', f: f %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
            <%= f.submit "登録する", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/customers/create.js.erb
$('.form-field').val("");
$('#customerModal').modal('hide');
$('.customer_index').html("<%= escape_javascript(render 'customers', customers: @customers) %>")

app/views/customers/edit.html.erb
<h2>顧客情報編集</h2>
<%= form_with model: @customer, url: customer_path, local: true do |f| %>
  <%= render 'form', f: f %>
  <%= f.submit "更新" %>
<% end %>

app/views/customers/index.html.erb
<div class="container">
  <div class="">
    <p id="notice"><%= notice %></p>
    <ul class="area-order">
      <li><h2>顧客一覧</h2></li>
      <li>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#customerModal">
          顧客登録
        </button>
      </li>
      <li>
        <div class="search-form mt-2">
          <%= form_with url: customers_path, method: :get, local: true do |f| %>
            <%= f.text_field :keyword, value: @keyword %>
            <%= f.submit "検索" %>
          <% end %>
        </div>
      </li>
    </ul>
    <div class="customer_index">
      <%= render 'customers', customers: @serch_result %>
    </div>
    <div class="pagenate">
      <%= paginate @customers %>
    </div>
  </div>
</div>

<%= render partial: 'modal_customer', locals: {customer: @customer} %>

<div id="modal_book">
  <%= render partial: 'books/modal_book', locals: {book: @book} %>
</div>

app/views/customers/index.js.erb
console.log("<%= @book.customer.phone_num %>")
$('#modal_book').html("<%= escape_javascript( render partial: 'books/modal_book', locals: {book: @book}) %>")
$('#bookModal').modal('show')

app/views/customers/new.html.erb
<h2>新規顧客登録</h2>
<%= form_with model:@customer, url: customers_path, local: true do |f| %>
  <%= render 'form', f: f %>
  <%= f.submit "登録" %>
<% end %>

app/views/customers/show.html.erb
<div class="container">
  <h2>顧客詳細</h2>
    <table class="table">
      <thead>
        <tr>
          <th>顧客ID</th>
          <th>名前</th>
          <th>電話番号</th>
          <th>住所</th>
          <th>アレルギー</th>
          <th>年齢</th>
          <th>備考</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th><%= @customer.id %></th>
          <th><%= @customer.name %></th>
          <th><%= @customer.phone_num %></th>
          <th><%= @customer.address %></th>
          <th><%= @customer.allergy %></th>
          <th><%= @customer.age %>歳</th>
          <th><%= @customer.note %></th>
        </tr>
      </tbody>
      <tfoot>
        <tr>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </tfoot>
      <%= link_to '編集', edit_customer_path(@customer), class: "customer_#{@customer.id} btn btn-outline-secondary" %>
      <%= link_to '削除', customer_path(@customer), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-outline-danger destroy_customer_#{@customer.id}"%>
    </table>
    <table class="table">
      <thead>
        <tr>
          <th>来店日時</th>
          <th>人数</th>
          <th>顧客アレルギー</th>
          <th>他アレルギー</th>
          <th>予約備考</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |b| %>
        <tr>
          <td><%= b.start_at %></td>
          <td><%= b.people %></td>
          <td><%= b.allergy %></td>
          <td><%= b.other_allergy %></td>
          <td><%= b.note %></td>
          <td></td>
        </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </tfoot>
    </table>
</div>