config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :customers
  resources :books
  resources :usages, only: [:index, :create, :destroy]
  resources :courses, only: [:index, :create, :destroy]
  resources :tablenumbers, only: [:index, :create, :destroy]
  root :to => "homes#top"
  get "/about" => "homes#about"

  #顧客検索
  get 'search' => 'customers#search'

  # get ''
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :customer
  belongs_to :course, optional: true
  belongs_to :usage, optional: true
  belongs_to :tablenumber, optional: true
  accepts_attachments_for :tablenumbers
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :books
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :books, dependent: :destroy

  def self.search(keyword)
    where(["name like? OR phone_num like?", "%#{keyword}%", "%#{keyword}%"])
  end
end

app/models/tablenumber.rb
class Tablenumber < ApplicationRecord
  has_many :books
  validates :name, presence: true
end

app/models/usage.rb
class Usage < ApplicationRecord
  has_many :books
  validates :name, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_admin!

  def new
    @book = Book.new
  end

  def index
    @book = Book.new
      search_date = Date.today
      @books = Book.where(start_at: search_date.in_time_zone.all_day)
      @customer = Customer.new
      @customers = Customer.all
      @tablenumbers = Tablenumber.all
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if book_params[:date] == nil
      @book.tablenumber_id = book_params[:tablenumber_id]
    elsif book_params[:date] != nil && !book_params[:date].empty? && !book_params[:time].empty?
      @visit = book_params[:date] +" "+ book_params[:time]
      @book.start_at = @visit.to_datetime
      @book.people = book_params[:people]
      @book.allergy = book_params[:allergy]
      @book.other_allergy = book_params[:other_allergy]
      @book.note = book_params[:note]
    end

    if @book.save
      redirect_to books_path, notice: "予約情報が更新されました"
    end
  end

  def create
    customer = Customer.find_by("phone_num=? or name=?",book_params[:phone_num],book_params[:name])
    if customer.blank?
      customer = Customer.new(phone_num: book_params[:phone_num],name: book_params[:name], allergy: book_params[:allergy])
      if customer.save
        book = customer.books.new(people: book_params[:people], note: book_params[:note], allergy: book_params[:allergy], other_allergy: book_params[:other_allergy])
        @visit = book_params[:date] +" "+ book_params[:time]
        book.start_at = @visit.to_datetime
        book.save
        redirect_to books_path
      else
        render index
      end
    else
      book = customer.books.new(people: book_params[:people], note: book_params[:note], allergy: book_params[:allergy], other_allergy: book_params[:other_allergy])
      @visit = book_params[:date] +" "+ book_params[:time]
      book.start_at = @visit.to_datetime
      if book.save
        redirect_to books_path
      else
        redirect_to customers_path(phone_num:book_params[:phone_num], name: book_params[:name] )
      end
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "予約は取り消されました"
  end

private
  def book_params
    params.require(:book).permit(:phone_num, :name, :people, :allergy, :note, :date, :time, :other_allergy, :tablenumber_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/tally_controller.rb
class TallyController < ApplicationController
end

app/controllers/usages_controller.rb
class UsagesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @usage = Usage.new
    @usages = Usage.all
  end

  def create
    @usage = Usage.new(course_params)
    @usage.save
    @usages = Usage.all
  end

  private
  def course_params
    params.require(:usage).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_courses_helper.rb
module BookCoursesHelper
end

app/helpers/book_usages_helper.rb
module BookUsagesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/customer_books_helper.rb
module CustomerBooksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/table_nums_helper.rb
module TableNumsHelper
end

app/helpers/tablenumbers_helper.rb
module TablenumbersHelper
end

app/helpers/tally_helper.rb
module TallyHelper
end

app/helpers/usages_helper.rb
module UsagesHelper
end

app/views/books/_books.html.erb
  <table class="table">
    <thead>
      <tr>
        <th>TN</th>
        <th>名前</th>
        <th>来店予定</th>
        <th>人数</th>
        <th>顧客アレルギー</th>
        <th>他アレルギー/NG</th>
        <th>予約備考</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody class="tbody">
      <% books.each do |b| %>
        <tr>
          <td>
            <%= form_with model: b, url: book_path(b) do |f| %>
              <%= f.select :tablenumber_id, @tablenumbers.map{ |tablenumber| [tablenumber.name, tablenumber.id] } %>
              <%= f.submit "TN更新", class: "btn btn-primary" %>
            <% end %>
          </td>
          <td><%= link_to b.customer.name, customer_path(b.customer), class: "b_customer_#{b.customer}" %> 様</td>
          <td>
            <% if b.start_at.present? %>
              <%= b.start_at.strftime("%Y年 %m月 %d日 %X") %>
            <% end %>
          </td>
          <td><%= b.people %>人</td>
          <td><%= b.allergy %></td>
          <td><%= b.other_allergy %></td>
          <td><%= b.note %></td>
          <td><%= link_to '詳細', book_path(b), class: "b_#{b.id} btn btn-outline-info" %></td>
          <td><%= link_to '編集', edit_book_path(b), class: "b_#{b.id} btn btn-outline-secondary" %></td>
          <td><%= link_to '削除', book_path(b), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-outline-danger destroy_b_#{b.id}"%></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </tfoot>
  </table>

app/views/books/_form.html.erb
<%= f.label :phone_num %><br>
<% if book.customer.nil? %>
  <%= f.telephone_field :phone_num %>（ハイフンなし）<br>
<% else %>
  <%= f.telephone_field :phone_num, value: book.customer.phone_num %>（ハイフンなし）<br>
<% end %>
<%= f.label :name %><br>
<%= f.text_field :name, autofocus: true %><br>
<%= f.label :date, class: 'control-label' %>
<%= f.date_field :date, class: 'form-control' %>
<%= f.label :time, class: 'control-label' %>
<%= f.time_field :time, class: 'form-control' %>
<%= f.label :people %><br>
<%= f.number_field :people %><br>

<%= f.label :allergy %><br>
<%= f.text_field :allergy %><br>

<%= f.label :other_allergy %><br>
<%= f.text_field :other_allergy %><br>

<%= f.label :note %><br>
<%= f.text_area :note %><br>

app/views/books/_form_edit.html.erb
<%= f.label :phone_num %><br>
<%= book.customer.phone_num %><br>
<%= f.label :name %><br>
<%= book.customer.name %><br>
<%= f.label :date, class: 'control-label' %>
<%= f.date_field :date, value: f.object.start_at.strftime("%Y-%m-%d"), class: 'form-control' %>
<%#= f.date_field :date, class: 'form-control' %>
<%= f.label :time, class: 'control-label' %>
<%= f.time_field :time, value: f.object.start_at.strftime("%X"), class: 'form-control' %>
<%#= f.time_field :time, class: 'form-control' %>
<%= f.label :people %><br>
<%= f.number_field :people %><br>

<%= f.label :allergy %><br>
<%= f.text_field :allergy %><br>

<%= f.label :other_allergy %><br>
<%= f.text_field :other_allergy %><br>

<%= f.label :note %><br>
<%= f.text_area :note %><br>

app/views/books/_modal_book.html.erb
<!-- Modal -->
<div class="modal fade" id="bookModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">新規予約登録</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with model: book, local: true do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= render 'books/form', {f: f, book: book} %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          <%= f.submit "登録する", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/create.js.erb
$('#input').val("");
$('#exampleModal').modal('hide');
$('.books').html("<%= escape_javascript(render 'books', books: @books) %>")

app/views/books/date_book.html.erb
<% @books.each do |book| %>
  <%#= book.TN %>
  <p><%= book.customer.name %>様</p>

<% end %>




<%= link_to "back", books_path, data: {"turbolinks"=>false} %>

app/views/books/edit.html.erb
<div class="container">
<h2>予約編集</h2>
  <%= form_with model: @book, url: book_path do |f| %>
    <%= render 'form_edit', f: f, book: @book %>
    <%= f.submit "更新" %>
  <% end %>
</div>

app/views/books/index.html.erb
<div class="container">
      <ul class="area-order">
        <li>
            <h2>本日の予約</h2>
        </li>
        <li>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#bookModal">
            予約登録
          </button>
        </li>
      </ul>
    <div class="main col-12">
      <%= render 'books', books: @books %>
    </div>
    <div class="sidebar col-12">
      <div id="calendar"></div>
    </div>
</div>

<!-- Modal -->
<div id="modal_book">
  <%= render partial: 'modal_book', locals: {book: @book} %>
</div>

app/views/books/new.html.erb
<h2>新規予約登録</h2>
  <%= form_with model:@book do |f| %>
    <%= render 'form', f: f %>
    <%= f.submit "登録" %>
  <% end %>

app/views/books/show.html.erb
<div class="container">
  <h2>予約詳細</h2>
  <a class="btn btn-primary" href="/books" role="button">予約一覧へ戻る</a>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>TN</th>
        <th>名前</th>
        <th>電話番号</th>
        <th>来店予定</th>
        <th>人数</th>
        <th>顧客アレルギー</th>
        <th>他アレルギー/NG</th>
        <th>備考</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @book.customer.id %></td>
        <td></td>
        <td><%= @book.customer.name %></td>
        <td><%= @book.customer.phone_num %></td>
        <td><%= @book.start_at.strftime("%Y年 %m月 %d日 %X") %></td>
        <td><%= @book.people %></td>
        <td><%= @book.customer.allergy %></td>
        <td><%= @book.other_allergy %></td>
        <td><%= @book.note %></td>
        <td><%= link_to '編集', edit_book_path(@book), class: "b_#{@book.id} btn btn-outline-secondary btn-block" %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/usages/_usages.html.erb
<% usages.each do |c| %>
  <div class="card mb-1">
    <div class="card-body">
      <p class="card-text"><%= c.name %></p>
    </div>
  </div>
<% end %>

app/views/usages/create.js.erb
$('#usage_name').val("");
$('#exampleModal').modal('hide');
$('.usages').html("<%= escape_javascript(render 'usages', usages: @usages) %>")

app/views/usages/index.html.erb
<h2>コース一覧</h2>
<div class="container mt-5">
  <div class="row">
    <div class="col-3 sidebar offset-1">
<!--新規コース登録ボタン-->
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  利用目的登録
</button>
    </div>
    <div class="col-5 sidebar usages offset-2">
      <%= render 'usages', usages: @usages %>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">新規利用目的登録</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with model: @usage do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :name, "利用目的" %>
            <%= f.text_field :name, autofocus: true %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
          <%= f.submit "登録する", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>