config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :customers
  resources :books
  resources :usages, only: [:index, :create, :destroy]
  resources :courses, only: [:index, :create, :destroy]
  resources :tablenumbers, only: [:index, :create, :destroy]
  root :to => "homes#top"
  get "/about" => "homes#about"

  #顧客検索
  get 'search' => 'customers#search'

  # get ''
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :customer
  belongs_to :course, optional: true
  belongs_to :usage, optional: true
  belongs_to :tablenumber, optional: true
  accepts_attachments_for :tablenumbers
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :books
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :books, dependent: :destroy

  def self.search(keyword)
    where(["name like? OR phone_num like?", "%#{keyword}%", "%#{keyword}%"])
  end
end

app/models/tablenumber.rb
class Tablenumber < ApplicationRecord
  has_many :books
  validates :name, presence: true
end

app/models/usage.rb
class Usage < ApplicationRecord
  has_many :books
  validates :name, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_admin!

  def new
    @book = Book.new
  end

  def index
    @book = Book.new
      search_date = Date.today
      @books = Book.where(start_at: search_date.in_time_zone.all_day)
      @customer = Customer.new
      @customers = Customer.all
      @tablenumbers = Tablenumber.all
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if book_params[:date] == nil
      @book.tablenumber_id = book_params[:tablenumber_id]
    elsif book_params[:date] != nil && !book_params[:date].empty? && !book_params[:time].empty?
      @visit = book_params[:date] +" "+ book_params[:time]
      @book.start_at = @visit.to_datetime
      @book.people = book_params[:people]
      @book.allergy = book_params[:allergy]
      @book.other_allergy = book_params[:other_allergy]
      @book.note = book_params[:note]
    end

    if @book.save
      redirect_to books_path, notice: "予約情報が更新されました"
    end
  end

  def create
    customer = Customer.find_by("phone_num=? or name=?",book_params[:phone_num],book_params[:name])
    if customer.blank?
      customer = Customer.new(phone_num: book_params[:phone_num],name: book_params[:name], allergy: book_params[:allergy])
      if customer.save
        book = customer.books.new(people: book_params[:people], note: book_params[:note], allergy: book_params[:allergy], other_allergy: book_params[:other_allergy])
        @visit = book_params[:date] +" "+ book_params[:time]
        book.start_at = @visit.to_datetime
        book.save
        redirect_to books_path
      else
        render index
      end
    else
      book = customer.books.new(people: book_params[:people], note: book_params[:note], allergy: book_params[:allergy], other_allergy: book_params[:other_allergy])
      @visit = book_params[:date] +" "+ book_params[:time]
      book.start_at = @visit.to_datetime
      if book.save
        redirect_to books_path
      else
        redirect_to customers_path(phone_num:book_params[:phone_num], name: book_params[:name] )
      end
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "予約は取り消されました"
  end

private
  def book_params
    params.require(:book).permit(:phone_num, :name, :people, :allergy, :note, :date, :time, :other_allergy, :tablenumber_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_courses_helper.rb
module BookCoursesHelper
end

app/helpers/book_usages_helper.rb
module BookUsagesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/table_nums_helper.rb
module TableNumsHelper
end

app/helpers/tablenumbers_helper.rb
module TablenumbersHelper
end

app/helpers/tally_helper.rb
module TallyHelper
end

app/helpers/usages_helper.rb
module UsagesHelper
end

app/views/layouts/_header.html.erb
<h1><a href="/"><%= image_tag "CI-BANK_text_logo.png", class: "logo", alt: "CI-BANKホーム" %></a></h1>
<% if admin_signed_in? %>
  <div id="hm-icon">
    <a class="menu-trigger" href="#">
      <span></span>
      <span></span>
      <span></span>
    </a>
  </div>
  <nav id="sp-menu">
    <ul class="nav-links">
      <li>
        <strong><%= link_to "予約一覧", books_path, data: {"turbolinks"=>false}, class: "link btn-flat-vertical-border" %></strong>
      </li>
      <li>
        <strong><%= link_to "顧客一覧", customers_path, class: "link btn-flat-vertical-border" %></strong>
      </li>
      <li>
        <strong><%= link_to "テーブルナンバー", tablenumbers_path, class: "link btn-flat-vertical-border"  %></strong>
      </li>
      <li>
        <strong><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "link btn-flat-vertical-border"  %></strong>
      </li>
    </ul>
  </nav>
<% else %>
  <nav>
    <ul class="nav-links">
      <li>
        <%= link_to "ログイン", new_admin_session_path, class: "link btn-flat-vertical-border" %>
      </li>
    </ul>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>CI-Bank</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8" />
    <%= favicon_link_tag "CI-BANK_logo.png" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sawarabi+Gothic&display=swap" rel="stylesheet">
  </head>

  <body data-turbolinks="false">
      <div class="page-header wrapper">
        <%= render 'layouts/header' %>
      </div>
      <%= yield %>
      <%= render 'layouts/footer' %>
    <script src="layouts/jquery.min.js"></script>
    <script src="layouts/script.js"></script>
  </body>
</html>